spring.application.name=finance-manager
spring.datasource.url=jdbc:postgresql://localhost:5433/finance_db
spring.datasource.username=finance_user
spring.datasource.password=finance_password
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8087

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

